/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AStringExpression extends PExpression
{
    private TStrLit _strLit_;

    public AStringExpression()
    {
        // Constructor
    }

    public AStringExpression(
        @SuppressWarnings("hiding") TStrLit _strLit_)
    {
        // Constructor
        setStrLit(_strLit_);

    }

    @Override
    public Object clone()
    {
        return new AStringExpression(
            cloneNode(this._strLit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringExpression(this);
    }

    public TStrLit getStrLit()
    {
        return this._strLit_;
    }

    public void setStrLit(TStrLit node)
    {
        if(this._strLit_ != null)
        {
            this._strLit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strLit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strLit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strLit_ == child)
        {
            this._strLit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strLit_ == oldChild)
        {
            setStrLit((TStrLit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
